### ISSUE TITLE
`|` character is misinterpreted in tables

### ISSUE THREAD

**Issue by mpvharmelen** [github/cmark#100]
See https://github.com/github/markup/issues/1206.

This code:
```
`\|`
```
Is rendered as `\|`.

This behaviour should not be different in a table, where the same code is now rendered as follows:

 A | B 
---|---
`C`|`\|`

To get the original rendering, the following code is needed:
```
`\\|`
```

 A | B 
---|---
`C`|`\\|`

Moreover, leaving out the `\` breaks the table:

```
A | B
---|---
C|the `|` is misinterpreted
```

A | B
---|---
C|the `|` is misinterpreted

**Comment by mpvharmelen** [comment]
The end is found here:
https://github.com/github/cmark/blob/e9a231f3a03d432d59ba209028f170d0eac423a5/extensions/ext_scanners.c#L676

https://github.com/github/cmark/blob/e9a231f3a03d432d59ba209028f170d0eac423a5/extensions/ext_scanners.c#L648

But it does not account for backtick characters.

**Comment by kivikakk** [comment]
This has been explored repeatedly at length, and the behaviour will not change in the future.

For history: #18, #19, #21, #24, #41.
