### ISSUE TITLE
Old Tags Lost?

### ISSUE THREAD

**Issue by codecaffeine** [github/cmark#108]
Hey, it looks like the tags before `0.27.1` have been removed. We’re currently using a dependency manager that references the `0.24.1` tag and it started failing today because it can’t find that tag anymore. Is there any way to restore the old tags?

**Comment by kivikakk** [comment]
There's been an issue with repositories being moved and renamed — can you check your remote?  I suspect you're using https://github.com/jgm/cmark.git, which recently has started pointing here after some repository renaming and forking that happened in the upstream repo.  I think you actually want https://github.com/commonmark/cmark.git.  Give it a try and let me know how it works out for you.

**Comment by codecaffeine** [comment]
@kivikakk Yup, that was the issue. Thanks!
