### ISSUE TITLE
Horizontal tables

### ISSUE THREAD

**Issue by hypothermic** [github/cmark#113]
I've searched through the documentation however it doesn't seem to be possible to make horizontal tables (see screenshot:)
![image](https://i.imgur.com/R0eMCZi.png)
Any plans to add this feature?

**Comment by kivikakk** [comment]
:wave: Indeed, it's not possible; the [spec for tables](https://github.github.com/gfm/#tables-extension-) is pretty limited, but we plan to keep it that way for simplicity's sake. If you're getting really complicated with your tables, it'd be better to do it in HTML.
