### ISSUE TITLE
Allow markdown inside a table-<td>

### ISSUE THREAD

**Issue by tordans** [github/cmark#12]
Is there a change you will extend your markdown flavor to allow markdown inside a table?

Example

<table><tr><td>
**My Markdown** [Link](#Link)
</td><tr></table>

```
<table><tr><td>
**My Markdown** [Link](#Link)
</td><tr></table>
```

**Comment by kivikakk** [comment]
The HTML blocks from the Markdown block with newlines:

```markdown
<table><tr><td>

**My Markdown** [Link](#Link)

</td><tr></table>
```

Produces:

> <table><tr><td>
> 
> **My Markdown** [Link](#Link)
> 
> </td><tr></table>
