### ISSUE TITLE
Class & ID

### ISSUE THREAD

**Issue by Mottie** [github/cmark#13]
The spec now shows that HTML with classes & ID's are allowed ([see example 120](https://github.github.com/gfm/#example-120)), but it appears that both are still being stripped away:

The following example would have red text, if this were allowed:

```html
<div class="text-red">test</div>
```

<div class="text-red">test</div>

**Comment by kivikakk** [comment]
This is stripped away by GitHub.com's user content stack as part of our general security flow, not GitHub's CommonMark implementation, which does preserve the class:

```bash
root@a03fe5b068d4:/src/cmark# cat document.md
<div class="text-red">test</div>
root@a03fe5b068d4:/src/cmark# build/src/cmark document.md
<div class="text-red">test</div>
root@a03fe5b068d4:/src/cmark#
```
