### ISSUE TITLE
.editorconfig & tabsize no longer respected?

### ISSUE THREAD

**Issue by leeoniya** [github/cmark#15]
Hey guys,

I believe `.editorconfig` support broke recently. Is this a resuly of switching to the cmark stack? Tabsize doesnt seem to be respected any more causing rendering issues withon code snippets that worked several days ago: https://github.com/leeoniya/domvm/blob/2.x-dev/README.md (for example, EOL comments are now misaligned).

Is this something that'll come back or permanently gone?

**Comment by kivikakk** [comment]
Hi there! This repository isn't for issues regarding GitHub's Markdown support in general or rendering thereof, but rather for issues regarding our fork of the `cmark` C implementation itself. Please [reach out to our support team](https://github.com/contact) with questions like this.

Thanks! :heart: :sparkles:

**Comment by leeoniya** [comment]
k will do. thx.
