### ISSUE TITLE
Numbered lists with sub-lists

### ISSUE THREAD

**Issue by radar** [github/cmark#16]
When I have a number list like this:

```
1. First point
  1. First point, sub-point 1
  1. First point, sub-point 2
  1. First point, sub-point 3
2. Second point
```

I would expect it to render like this:

```html
<ol>
  <li>
    <p>First point</p>
    <ol>
      <li>First point, sub-point 1</li>
      <li>First point, sub-point 2</li>
      <li>First point, sub-point 3</li>
    </ol>
  </li>
  <li><p>Second point</p></li>
</ol>
```

Instead it renders like this:

```html
<ol>
  <li><p>First point</p></li>
  <li>First point, sub-point 1</li>
  <li>First point, sub-point 2</li>
  <li>First point, sub-point 3</li>
  <li><p>Second point</p></li>
</ol>
```

I see in the spec that you supported nested unordered lists, but I couldn't see anything for nested numbered lists like this. Maybe I didn't look hard enough?

I would attempt fixing this myself, but I am not that great at C.

**Comment by kivikakk** [comment]
Nested numbered lists are fine, but you need some more indentation.

The spec says a lot about indentation — see everything under http://spec.commonmark.org/0.27/#example-215 — but in short, you need to indent the sublist to the same level as the start of the text of the parent list.

i.e.:

```markdown
Failure:

1. abc
  1. this won't work because the "1" doesn't align with the "a" above.

Success:

1. abc
   1. this will work
```

Renders as follows:

> Failure:
>
> 1. abc
>   1. this won't work because the "1" doesn't align with the "a" above.
>
> Success:
>
> 1. abc
>    1. this will work

**Comment by radar** [comment]
Thank you very much :)
