### ISSUE TITLE
Compiler warnings on win64 with mingw-w64

### ISSUE THREAD

**Issue by jeroenooms** [github/cmark#2]
I would really like to eliminate these. The problem is we store an `unsinged char` in a `void *` but on Windows 64 these have different size.
```
Found the following significant warnings:
  cmark/blocks.c:395:41: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  cmark/inlines.c:511:41: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  cmark/inlines.c:525:45: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
```

**Comment by kivikakk** [comment]
Just catching up on this: did the branch at https://github.com/github/cmark/tree/kivikakk/win32 quell these warnings for you? If so, I'll merge!

**Comment by kivikakk** [comment]
I'll merge (what is now) #5 anyway so it at least builds on MSVC10 — please let me know if this doesn't fix it for mingw-w64 as well.

**Comment by jeroenooms** [comment]
Seems to be fixed, thanks!
