### ISSUE TITLE
Ugly header hashes/fragments

### ISSUE THREAD

**Issue by stevenvachon** [github/cmark#22]
```markdown
## a & b
```
more or less becomes
```html
<h2 id="a--b"><a href="#a--b">a & b</a></h2>
```
where `#a--b` is definitely ugly.

**Comment by kivikakk** [comment]
fwiw, this isn't part of our CommonMark implementation, it's part of GitHub's user content stack. We're unlikely to the rules for changing header text to IDs it because a lot of existing e.g. READMEs depend on it.

**Comment by stevenvachon** [comment]
It was already changed with the switch to cmark from marked.

**Comment by kivikakk** [comment]
I'm not sure I understand what you mean. We've always had this hash/fragment generation (at least for ~5 years, judging by our own internal Markdown documents which have manually written-out tables of contents), the change from Sundown to CommonMark has nothing to do with it.
