### ISSUE TITLE
Problem rendering list items with links followed by a single word

### ISSUE THREAD

**Issue by wincent** [github/cmark#26]
```
- [Foo]: Description.

[Foo]: http://example.com/
```

Renders as:

```
<ul>
<li></li>
</ul>
```

Live repro (currently repros on this issue on May, 12th, 2017):

- [Foo]: Description

Work around is to use more than one word after link:

```
- [Foo]: Longer description.

[Foo]: http://example.com/
```

Renders as:

```
<ul>
<li><a href="Description">Foo</a>: Longer description.</li>
</ul>
```

Live demo:

- [Foo]: Longer description.

[Foo]: http://example.com/

Original discovered while investigating: https://github.com/wincent/masochist/issues/101

**Comment by kivikakk** [comment]
I can reproduce this upstream so properly this is a bug with jgm/cmark. Let's see what's going on here.

If we [plug your first example](http://spec.commonmark.org/dingus/?text=-%20%5BFoo%5D%3A%20Description.%0A%0A%5BFoo%5D%3A%20http%3A%2F%2Fexample.com%2F%0A) into the CommonMark.js demo, we can see it's rendered the same — a list with one, empty item.

If we add `[Foo]` above, like this:

``` markdown
[Foo]

- [Foo]: Description.

[Foo]: http://example.com/
```

We get the following:

``` html
<p><a href="Description.">Foo</a></p>
<ul>
<li></li>
</ul>
```

The nature of the issue has become clear: the list item's content is being interpreted as a reference link definition. (The first definition takes priority.)

There's nothing specifically disallowing these from occurring as children of other container blocks, such as lists, so the same parsing rules apply.

It's easy enough to prevent this from happening by putting a backslash (`\`) before the colon:

``` md
- [Foo]\: Description.

[Foo]: http://example.com/
```
