### ISSUE TITLE
autolink not following spec?

### ISSUE THREAD

**Issue by aidantwoods** [github/cmark#27]
www.example.com

---

https://github.github.com/gfm/#autolinks-extension- defines delimiting characters for an autolink:

> Autolinks can also be constructed without requiring the use of `<` and to `>` to delimit them, although they will be recognized under a smaller set of circumstances. All such recognized autolinks can only come after whitespace, or any of the delimiting characters `*`, `_`, `~`, `(`, and `[`.

However, as you can see (live repro)

[http://www.example.com

[www.example.com

(http://www.example.com

(www.example.com

are not treated in the same way (`[` appears to be ignored among valid delimiters).

---

Additionally, at the very top of this document an autolink has been rendered. However it has no such characters as a delimiter (because there are zero characters before it). Is `w` a delimiter in this case? Or perhaps the start of the string is a delimiter?

(zero characters do not count as whitespace per: https://github.github.com/gfm/#whitespace so the gfm spec should be clarified for this case).

(I'm asking as someone trying to write some implementation details based on the gfm spec, something I would gladly take those latter concerns to if github had a fork of the original CommonMark spec https://github.com/jgm/CommonMark 😉)

**Comment by kivikakk** [comment]
You're quite right about `[` — the spec is wrong here, and it shouldn't be included as one of the delimiters. Likewise, the start of a line is also a valid place for an autolink to appear, as you've rightly pointed out.

I'll amend the spec shortly to reflect both cases. Thank you!

**Comment by aidantwoods** [comment]
Might I suggest that the spec be amended to define an ASCII letter as the delimiter for auto links that include a scheme, and `w` as the delimiter for the extended www autolink? Then simply require the current delimiters to precede these new ones as a validity condition. 

This would avoid introducing two unprecedented occurrences into the spec:
1. Delimiters which are not consumed by the inline element
2. Zero width delimiters

The parser I'm writing would be able to cope with both of these with minimal changes, but possibly others may have difficulty trying to match spec without basically just redefining it as above.

**Comment by aidantwoods** [comment]
This would dispose of the zero width delimiter by just imposing something like "If a character proceeds a potential autolink, then it must be one of the following:" (and then just list the delimiters currently defined, incl. whitespace char).

**Comment by aidantwoods** [comment]
Current spec addresses the issues pointed out, closing :)
