### ISSUE TITLE
Table row alignment not available in the cmark AST

### ISSUE THREAD

**Issue by nafest** [github/cmark#28]
I am using cmark's AST to write a CommonMark renderer that renders with Skia ([directcmr](https://github.com/nafest/directcmr)). I am rendering tables with this fork but currently there is no way to access  the alignments field of the node_table struct. I'd suggest to add a getter for the row alignments.

**Comment by kivikakk** [comment]
Thanks for the suggestion! I'll go ahead and add a getter for the alignments now. (Also feel free to open PRs in future!)

**Comment by kivikakk** [comment]
Merged into master now; feel free to pull the changes into directcmr, or let me know if you want me to bump the version number. (Otherwise I'll wait until we've accumulated some more changes.)

**Comment by kivikakk** [comment]
(An example use can be seen in the commit message of 2915df2.)

**Comment by nafest** [comment]
Thank you for adding this.
