### ISSUE TITLE
Trim extra spaces in table cells

### ISSUE THREAD

**Issue by jgm** [github/cmark#3]
With the following input
```
| hi | lo |
| -- | -- |
| 5  |  7 |
```
`cmark -t xml -e table` yields
```
  <table>
    <table_header>
      <table_cell>
        <text> hi </text>
      </table_cell>
      <table_cell>
        <text> lo </text>
      </table_cell>
    </table_header>
    <table_row>
      <table_cell>
        <text> 5  </text>
      </table_cell>
      <table_cell>
        <text>  7 </text>
      </table_cell>
    </table_row>
  </table>
```
This renders fine, but it would be better, I think, to trim the leading and trailing spaces in the table cells before parsing as inlines.  (This doesn't cause any real problems, because in HTML the leading and trailing spaces in td elements are ignored anyway.  But, conceptually, the leading and trailing spaces are not part of the content; they're just there to fill out the cell, and often just to help things line up on the page.)

**Comment by kivikakk** [comment]
It's ever so slightly tricky because we there's no "before parsing as inlines" step — the entire _line_ is parsed as one inline, and then we split it up. (This is the basis of correctly parsing table cells with e.g. inline code blocks with pipes inside them.) Still, not too hard — will have a look.

**Comment by jgm** [comment]
+++ Yuki Izumi [Dec 08 16 17:42 ]:
>   It's ever so slightly tricky because we there's no "before parsing as
>   inlines" step — the entire line is parsed as one inline, and then we
>   split it up. (This is the basis of correctly parsing table cells with
>   e.g. inline code blocks with pipes inside them.) Still, not too hard —
>   will have a look.

Oh, I see.

Do you have a draft spec of the table format you're parsing?

There's a big conceptual issue here.  It's part of the spec
that block parsing is prior to inline parsing, so for
example

    <a href="a
    # b">

    comes out as

    <p>&lt;a href=&quot;a</p>
    <h1>b&quot;&gt;</h1>

Since table cells are block level elements, the natural
thing to do is to divide cells first, then parse for
inlines.

That would mean (most naturally) that

    | a` | `b |

comes out as a table with two cells, rather than one.

There's an issue, then, that would need to be dealt with
about how to include code spans containing bar characters.
I believe one approach others have taken is to allow ad-hoc
backslash escaping of bar in table contexts.

Anyway, it sounds as if you take another approach, on
which the example above would be a table with one cell.
As you can see from this thread
https://talk.commonmark.org/t/parsing-strategy-for-tables/2027/40
I'm sympathetic to your approach, though I'm very much
undecided on this issue.  Anyway, this is the kind of
decision that would really benefit from some discussion;
please contribute there if you have opinions about this.

**Comment by kivikakk** [comment]
@jgm: thanks, I've posted at the thread and will follow the discussion there. Indeed, the table extension as originally implemented by Mathieu did break on pipes, and escaping with backslashes was the tool to get around this. In practice this broke people's use of tables on GitHub — we had enough cases where a table would be broken because of embedded pipe(s) in table cells, as our old parser would accept them.
