### ISSUE TITLE
Installing extensions on linux (using `make install`)

### ISSUE THREAD

**Issue by Jinmo** [github/cmark#31]
I found that `make install` does not install `libcmark-gfmextensions.so`, and there's no way to install the library. It would be good if there's a way to install it (like `make install_extensions`)!

**Comment by kivikakk** [comment]
Thank you for the report! I've fixed this up (it's part of the regular `make install` — the installed binary is statically linked to extensions, so I figure it makes sense to install the separate libraries at the same time too). I'll push a new version number shortly.
