### ISSUE TITLE
GFM Version check macro

### ISSUE THREAD

**Issue by foonathan** [github/cmark#33]
Please add something like `CMARK_GFM_VERSION` to detect whether you use this fork.

**Comment by kivikakk** [comment]
I'm thinking of just adding something like:

``` c
#define CMARK_GFM_VERSION
```

to [`src/cmark_version.h.in`](https://github.com/github/cmark/blob/fdea2425ad7c10c8971e41f6858aa3b4dc2f0879/src/cmark_version.h.in).

I was going to define it as `@PROJECT_VERSION_GFM@` originally, but I was originally thinking of resetting that when we rebase onto a later upstream. Alternatively, we can keep `@PROJECT_VERSION_GFM@` monotonically increasing regardless of the upstream version. What do you think?

**Comment by foonathan** [comment]
I don't actually care about the exact version, I just want to detect it. Currently I use `CMARK_NODE_TYPE_PRESENT`...

**Comment by kivikakk** [comment]
Alrighty! Have added in f484a2c.

**Comment by foonathan** [comment]
Thx!
