### ISSUE TITLE
Document Alerts

### ISSUE THREAD

**Issue by mfridman** [github/cmark#350]
Any plans to update the documentation to include the custom extension of the blockquote syntax? I believe this is referred to as "Alerts".

Original discussion: https://github.com/orgs/community/discussions/16925

Relevant GH docs: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by wooorm** [comment]
(I Don't work at gh)

This spec is about a fork of commonmark, that deals with extensions to how to parse markdown (e.g., tables).

Alerts are not implemented in this project. They don't relate to their parser. They don't relate to syntax. So they're not here.

They are implemented as a post processing step on a sort of "DOM" version of the resulting document.

GH does many things there. Lots of extra things. Documented on their help website

**Comment by mfridman** [comment]
Great, thanks for the clarification. Closing due to human error, sorry about that.

**Comment by froh** [comment]
wouldn't it nonetheless be lovely if the repo hosting the [offical gfm spec](https://github.github.com/gfm/) was complete?

as a gfm user, I couldn't care less if the Alerts are handled with the md->html renderer or with in browser postprocessing.

point is: the spec is incomplete, and this repo hosts it.  right?
