### ISSUE TITLE
Eaten backslash in a code span

### ISSUE THREAD

**Issue by mity** [github/cmark#41]
Currently the `spec.txt` contains this example for table extension:

```````````````````````````````` example table
| f\|oo  |
| ------ |
| b `\|` az |
| b **\|** im |
.
<table>
<thead>
<tr>
<th>f|oo</th>
</tr>
</thead>
<tbody>
<tr>
<td>b <code>|</code> az</td>
</tr>
<tr>
<td>b <strong>|</strong> im</td>
</tr></tbody></table>
````````````````````````````````

I believe the example (and perhaps even the implementation if it follows it) is wrong. IMHO, the line ``| b `\|` az |`` should be converted to  `<td>b <code>\|</code> az</td>` and not `<td>b <code>|</code> az</td>` as the backslash is inside the code span.

See section 6.1 about Backslash escapes where the spec says:
> Backslash escapes do not work in code blocks, code spans, autolinks, or raw HTML

**Comment by kivikakk** [comment]
This question comes up a lot — the parsing order means the backslash hits the table (block) parser first and is never seen by the code span parser. See #24 and github/markup#1078!

**Comment by mity** [comment]
Ok. This is quite funny ;-) MD4C originally behaved more like that (with many corner cases left unsolved). But after seeing your arguments and discussion on https://talk.commonmark.org/t/parsing-strategy-for-tables/2027/46, I changed it to follow your strategy.

Yesterday I started to look how to make MD4C extensions more compatible with GFM extensions after the migration to Cmark-gfm and found this.

I can live either way (both have some pros and cons). Just tell me, do you consider the current behavior as final and decided, or is it still some ongoing discussion and it may change in a foreseeable future again?

**Comment by kivikakk** [comment]
Ahh, I see! Alas 😥 

I do think this is how we'll leave it for the foreseeable future. I was unhappy with leaving it like this (because it's pretty ugly), but it's simpler, and more importantly, it's how our pre-CommonMark parser worked, so this way we're at least maintaining backwards compatibility with syntax. So I think you can expect we won't change things on our end again.

**Comment by kivikakk** [comment]
Closing this as we're very unlikely to change this behaviour. Please let me know if you have further questions!
