### ISSUE TITLE
Support disabling inline HTML

### ISSUE THREAD

**Issue by DemiMarie** [github/cmark#44]
This is a feature request to support not parsing HTML at all.

**Comment by kivikakk** [comment]
We do not parse HTML; the CommonMark spec has some provisions for recoginising HTML in the document and altering the parser state accordingly, but that's all. You can disable output of tags so-recognised with safety options.

This is fairly important for our use case and we're unlikely to support such a feature in our own fork, as it would be a huge divergence from the spec.

**Comment by kivikakk** [comment]
Closing this as I think your request is covered by `--safe` (see below); if not, please hit me up again!

``` shell
$ echo -e "Hi <strong>there</strong>.\n\n<table></table>" | build/src/cmark-gfm --safe
<p>Hi <!-- raw HTML omitted -->there<!-- raw HTML omitted -->.</p>
<!-- raw HTML omitted -->
```
