### ISSUE TITLE
"www extended autolink" and "valid domain" definitions need rewording.

### ISSUE THREAD

**Issue by mity** [github/cmark#50]
The autolink extension specification contains this:

> An extended www autolink will be recognized when a valid domain is found. A valid domain consists of the text `www.`, followed by alphanumeric characters, underscores (`_`), hyphens (`-`) and periods (`.`). There must be at least one period, and no underscores may be present in the last two segments of the domain.

And later this:

> An extended url autolink will be recognised when one of the schemes `http://`, `https://`, or `ftp://`, followed by a valid domain, then zero or more non-space non-`<` characters according to extended autolink path validation.

I.e. accordingly to these, the extended url autolink should always have `www.` after the domain, but examples show differently. The definition of valid domain should be changed to not enforce `www.`, and that requirement should be moved to the definition of www autolink.

**Comment by kivikakk** [comment]
The live published spec was out-of-date due to a broken build process. The revised text is live now:

> An extended www autolink will be recognized when the text `www.` is found followed by a valid domain. A valid domain consists of alphanumeric characters, underscores (`_`), hyphens (`-`) and periods (`.`). There must be at least one period, and no underscores may be present in the last two segments of the domain.

And then:

> An extended url autolink will be recognised when one of the schemes `http://`, `https://`, or `ftp://`, followed by a valid domain, then zero or more non-space non-`<` characters according to extended autolink path validation.

**Comment by kivikakk** [comment]
Closing as fixed!
