### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by DemiMarie** [github/cmark#56]
Supported by, e.g. [pulldown-cmark](https://github.com/google/pulldown-cmark).

**Comment by blackst0ne** [comment]
Guys, is there any plan to add support of footnotes? 

```markdown
Hello world! [^1]
[^1]: This is written in English
```

**Comment by kivikakk** [comment]
I've been thinking about this a bit lately — it would be super useful, so I would like to get around to this, maybe even soon. (PRs of course gratefully accepted!)

**Comment by DemiMarie** [comment]
@kivikakk Would you also be able to add this to Comrak?

**Comment by kivikakk** [comment]
@DemiMarie that will certainly be the plan!
