### ISSUE TITLE
Spaces around info string?

### ISSUE THREAD

**Issue by ahmed-taj** [github/cmark#60]
The spec says:

> The line with the opening code fence may optionally contain some text following the code fence; this is trimmed of leading and trailing spaces and called the info string.

I wonder what `spaces` actually means to in this context? spaces only? spaces and tabs?

I usually check my assumptions using [GitHub Markdown API](https://api.github.com/markdown), but this time I got strange output!

**Output:**
```html
<pre lang="hey"><code>print 'Hello world!'
</code></pre>
```

**Input:**

    ```·→hey
    print 'Hello world!'
    ```
May someone explain what just happened?

-------
**NOTE**
`·` represents space
`→` represents tab

**Comment by kivikakk** [comment]
We use an option called `CMARK_OPT_GITHUB_PRE_LANG` in this fork to output code blocks in a style that github.com expects:

https://github.com/github/cmark/blob/07fe00f38e78846bc0760cb02a3b1441dffc9b6d/src/html.c#L186-L192

That aside, though, you're right that the spec is inconsistent; it says "trimmed of leading and trailing spaces" but the code calls `cmark_strbuf_trim`:

https://github.com/github/cmark/blob/07fe00f38e78846bc0760cb02a3b1441dffc9b6d/src/blocks.c#L312-L316

which trims anything matching `cmark_isspace`. I'll open a PR to the spec upstream to have this changed to "trimmed of leading and trailing whitespace" such that the code is correct.

**Comment by kivikakk** [comment]
▶️ https://github.com/commonmark/CommonMark/pull/505

**Comment by ahmed-taj** [comment]
@kivikakk Thanks

Well, another space-related thing is this:
https://github.com/github/cmark/blob/07fe00f38e78846bc0760cb02a3b1441dffc9b6d/test/spec.txt#L542-L546
However, I think the source code actually accepts both spaces and tabs (I don't understand how `re2c` works, though :smile:  )
https://github.com/github/cmark/blob/07fe00f38e78846bc0760cb02a3b1441dffc9b6d/src/scanners.re#L274-L278

**P.S:** should I open issues like this one in the original cmark repo?

**Comment by kivikakk** [comment]
You're right, this should say "spaces or tabs" specifically, not "spaces" (which is only `U+0020 SPACE`) nor "whitespace" (which would also newlines and other kinds of tabs/feeds). I'll add this to my PR at commonmark/CommonMark#505.

I think you definitely could open these on the upstream cmark repo, or directly on the `CommonMark` repo itself like I'm doing if you wanted to call it out as a problem with the spec.

**Comment by kivikakk** [comment]
commonmark/CommonMark#505 got merged, so these issues are hopefully fixed 👍
