### ISSUE TITLE
cmark_extension_api.h contains include for uninstalled header files

### ISSUE THREAD

**Issue by felixonmars** [github/cmark#62]
There are six header files installed:

```
cmark-gfm /usr/include/cmark.h
cmark-gfm /usr/include/cmark_export.h
cmark-gfm /usr/include/cmark_extension_api.h
cmark-gfm /usr/include/cmark_version.h
cmark-gfm /usr/include/cmarkextensions_export.h
cmark-gfm /usr/include/core-extensions.h
```

But in the file cmark_extension_api.h, two includes of other header files are present:
```
#include <render.h>
#include <buffer.h>
```

This makes the file unusable when building as a shared library, along with core-extensions.h which includes it.

**Comment by kivikakk** [comment]
Nice catch, thank you!
