### ISSUE TITLE
Autoidentifier in cmark-gfm are not backward compatible

### ISSUE THREAD

**Issue by xoofx** [github/cmark#68]
A followup of #65, it is not per se a real issue as @kivikakk  mentioned that it is currently done at HTML level on github, but the cmark-gfm seems to output its own identifiers (even if they get rewritten later)... But maybe this should still be consistent there?

Generated auto-identifiers for headings in `cmark-gfm` are different from  https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb as they are stripping `_` unlike the regexp `\w` which keeps the underscore.

See pull request here that was looking to modify this based on `cmark-gfm` results: https://github.com/lunet-io/markdig/pull/173

**Comment by kivikakk** [comment]
I'm a little lost; `cmark-gfm` doesn't output any header IDs:

```shell
~/github/cmark master$ cat test.md
# Hello

## Here are some headers

### Hi
~/github/cmark master$ build/src/cmark-gfm test.md
<h1>Hello</h1>
<h2>Here are some headers</h2>
<h3>Hi</h3>
```

Can you be precise as to what you're referring to? The reason our HTML pipeline ends up turning `# _a_` into an anchor with the ID `a` is because it occurs _after_ Markdown processing has completed entirely: it's operating on a HTML DOM which is essentially `<h1><em>a</em></h1>` — the underscores are not visible to it since they've been processed as emphasis.

**Comment by xoofx** [comment]
> I'm a little lost; cmark-gfm doesn't output any header IDs:

If you look at [babelmark](https://babelmark.github.io/?text=%23+_a_)

Or from the command line:
```
curl https://api.github.com/markdown -XPOST -d'{"text":"# _a_"}'
.
<h1>
  <a id="user-content-a" class="anchor" href="#a" aria-hidden><span aria-hidden class="octicon octicon-link"></span></a><em>a</em>
</h1>
```
It seems that the markdown API GitHub is more verbose than the plain cmark-gfm, so it may confuse people...

**Comment by kivikakk** [comment]
It's cmark-gfm-**based**, yes, but it also runs through GitHub's HTML pipeline. It's true that might be a bit confusing. Do you have any suggestions?

**Comment by xoofx** [comment]
> It's cmark-gfm-based, yes, but it also runs through GitHub's HTML pipeline. It's true that might be a bit confusing. Do you have any suggestions?

Oh, ok, I didn't get that the HTML processing was also occurring on the API (but obviously, if it is to match what is on GitHub, I should have thought about this), so then that's a problem on our side, sorry for the trouble!
