### ISSUE TITLE
Example 248: unclear why there can be 4 leading spaces for a list item

### ISSUE THREAD

**Issue by fredemmott** [github/cmark#70]
Simplified example (corresponding to `d` and `e` in the example):

```
   - foo with 3 leading spaces
    - bar with 4 leading spaces
```

`cmark-gfm` produces:

```
<ul>
<li>foo with 3 leading spaces</li>
<li>bar with 4 leading spaces</li>
</ul>
```

However, the specification says there may only be 0-3 leading spaces for list items, so, as I understand it, the second line is not an item. As indented code blocks can't interrupt paragraphs, it seems like it should be parsed as:

```
<ul>
<li>foo with 3 leading spaces - bar with 4 leading spaces</li>
</ul>
```

**Comment by fredemmott** [comment]
The indentation section on list items mentioned 1-3 spaces - however, the motivation section mentions:

> The problem is that such a rule, together with the rule allowing 1–3 spaces indentation of the initial list marker

Outside of the motivation section, I don't see anything saying that 1-3 spaces is only for the initial item.

**Comment by kivikakk** [comment]
This is part of the pure CommonMark spec, and might be better questioned over at [commonmark/CommonMark](https://github.com/commonmark/CommonMark).
