### ISSUE TITLE
Emoji support not documented

### ISSUE THREAD

**Issue by srawlins** [github/cmark#75]
You can do useful emoji on GitHub `:tada:` :tada:, yet not no Emoji extension is documented `:cry:` :cry:.

**Comment by kivikakk** [comment]
Emoji is not implemented as part of our Markdown stack; it's part of the user content stack that all content runs through, regardless of its source. `cmark` only covers the Markdown to HTML conversion.

**Comment by srawlins** [comment]
I see. Thanks for the explanation!
