### ISSUE TITLE
Problem in latest tag

### ISSUE THREAD

**Issue by dylanwh** [github/cmark#77]
It's not possible to rely on the libdir provided in the pkgconfig file in the latest tag.

Though it is fixed in afc9a17d359b25b8636ffa535ffe2a1cb1fbba01.
I'll just use the code in 'master' for my language binding.

(yes, of course I'm using your fork of cmark. Everyone loves GFM more than vanilla.)

**Comment by dylanwh** [comment]
Nevermind, it was user error. :-)

**Comment by dylanwh** [comment]
Or not, I see the .11 tag also doesn't work. Though before for some reason I was on .10

**Comment by kivikakk** [comment]
Hey there :wave: Can you clarify what issue you're encountering? (Is it the one fixed in #78?)

**Comment by dylanwh** [comment]
It's about upstream #236, where the @libdir@ variable was added the the pkgconfig file.
At the moment I can just base my binding on the master branch.

When I filed this I knew far less about all of this, feel free to close and chalk up to a confused developer.

Thanks for the prompt attention to both my issues!

**Comment by kivikakk** [comment]
No problems! 😄
