### ISSUE TITLE
Should libcmark-gfmextensions be listed in the pkgconfig file?

### ISSUE THREAD

**Issue by dylanwh** [github/cmark#78]
I see that I need to pass  -lcmark-gfmextensions if I want to be able to call core_extensions_ensure_registered() (and, of course, the extensions themselves).

Should that be listed in the pkgconfig file?

**Comment by kivikakk** [comment]
Yes! Totally, sorry, what an oversight on my behalf. I'll have this fixed quickly.

**Comment by kivikakk** [comment]
Fixed in e97b324. Let me know if you need another release for this soon.

**Comment by darkvn79** [comment]
i want come back to thank you  and i know you want help me this problem but i can't doing .  They're help me very more , thank
