### ISSUE TITLE
Cut a release for packaging

### ISSUE THREAD

**Issue by zmwangx** [github/cmark#9]
I learned about this fork from [the Engineering blog post](https://githubengineering.com/a-formal-spec-for-github-markdown/), and would love to add this to Homebrew (as well as use the extensions myself). A tag/release would be necessary for Homebrew though.

Would you please consider cutting a release? Thanks.

**Comment by kivikakk** [comment]
We're discussing internally how to handle versioning; I'll update here when I have some news!

**Comment by zmwangx** [comment]
Cool, thanks.

**Comment by sjackman** [comment]
Any update on tagging a stable release?
I'd suggest tagging a stable release with the version number
`0.27.1.gfm.0`

**Comment by kivikakk** [comment]
Thanks all; this has been done. [`0.27.1.gfm.0`](https://github.com/github/cmark/releases/tag/0.27.1.gfm.0) has been cut.

**Comment by zmwangx** [comment]
Thanks, submitted to Homebrew https://github.com/Homebrew/homebrew-core/pull/13089.

**Comment by kivikakk** [comment]
Thank you!
