### ISSUE TITLE
Single tilde in GFM spec

### ISSUE THREAD

**Issue by mpvharmelen** [github/cmark#99]
I thought https://github.com/github/cmark/issues/71#issuecomment-373181790 by @puzrin in was good and #84 shows this is a useful discussion. I'm opening this issue to continue the discussion.

The point @puzrin is making, is that the GFM spec should specify double tilde as the only way to strike-through text, _even though_ cmark supports any number of tildes.

@kivikakk says in https://github.com/github/cmark/issues/71#issuecomment-373176281:
> I understand that the intent of CM is to unify the dialects, but we've taken as much care as we have to implement the extensions we needed on top of CM without affecting core CommonMark compatibility.

So would it be a solution to change the GFM _spec_ to use double tilde only for strike-through to inspire new implementations of the GMF spec to be compatible with underscores, but leave the _implementation_ as is to not affect core CommonMark compatibility?

**Comment by kivikakk** [comment]
I understand where you're coming from. I'd be happy to go with this solution.

**Comment by kivikakk** [comment]
This is done; see https://github.github.com/gfm/#strikethrough-extension- for the latest.

**Comment by puzrin** [comment]
@kivikakk, @mpvharmelen  thanks!

**Comment by Crissov** [comment]
This issue can be closed, right? @mpvharmelen
